name: Security Scans

on:
  pull_request:
    branches: [ development, staging, production ]
  push:
    branches: [ development, staging, production ]
  schedule:
    - cron: '0 0 * * 1'

jobs:
  secret-scan:
    name: Secret Leak Detection (Gitleaks)
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-audit:
    name: Dependency Vulnerability Scan (Pip-audit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies & pip-audit
        run: |
          pip install pip-audit
          pip install pyspark loguru faker

      - name: Scan installed packages for CVEs
        run: pip-audit

  code-sast:
    name: Python SAST Security Audit (Bandit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: bandit -r src/ -ll -ii
